version: "3.9"

services:
  user:
    build: services/mock-http-service
    container_name: user_webflux
    ports:
      - "8083:8080"

  order:
    build: services/mock-http-service
    container_name: order_webflux
    ports:
      - "8084:8080"

  notification:
    build: services/mock-http-service
    container_name: notification_webflux
    ports:
      - "8085:8080"

  bff-graphql:
    build: services/bff-graphql
    container_name: bff-graphql
    ports: ["8081:8080"]
    depends_on: [user, order, notification]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health/readiness || exit 1
      # test: |
      #   wget --header="Content-Type: application/json" \
      #   --post-data='{"query": "query { dashboard {notifications orders user } }" }' \
      #   --output-document - \
      #   http://localhost:8080/graphql || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s # Time to wait for app to start
