version: "3.9"

services:
  user:
    build: services/mock-http-service
    container_name: user_webflux
    ports:
      - "8083:8080"

  order:
    build: services/mock-http-service
    container_name: order_webflux
    ports:
      - "8084:8080"

  notification:
    build: services/mock-http-service
    container_name: notification_webflux
    ports:
      - "8085:8080"

  bff-webflux:
    build: services/bff-webflux
    ports: ["8081:8080"]
#    depends_on: [user, order, notification]
